const classChanges = [
  { time: 0, target: ".p1", add: "highlight" },
  { time: 16, target: ".p2", add: "highlight" },
  { time: 35, target: ".p3", add: "highlight" },
  { time: 36, target: ".p4", add: "highlight" },
  { time: 41, target: ".p5", add: "highlight" },
  { time: 82, target: ".p6", add: "highlight" },
  { time: 117, target: ".p7", add: "highlight" },
  { time: 134, target: ".p8", add: "highlight" },
  { time: 151, target: ".p9", add: "highlight" },
  { time: 154, target: ".p10", add: "highlight" },
  { time: 164, target: ".p11", add: "highlight" },
  { time: 185, target: ".p12", add: "highlight" },
  { time: 186, target: ".p13", add: "highlight" },
  { time: 191, target: ".p14", add: "highlight" },
  { time: 195, target: ".p15", add: "highlight" },
  { time: 198, target: ".p16", add: "highlight" },
  { time: 200, target: ".p17", add: "highlight" },
  { time: 202, target: ".p18", add: "highlight" },
  { time: 223, target: ".p19", add: "highlight" },
  { time: 226, target: ".p20", add: "highlight" },
  { time: 265, target: ".p21", add: "highlight" },
  { time: 267, target: ".p22", add: "highlight" },
  { time: 272, target: ".p23", add: "highlight" },
  { time: 274, target: ".p24", add: "highlight" },
  { time: 306, target: ".p25", add: "highlight" },
  { time: 309, target: ".p26", add: "highlight" },
  { time: 333, target: ".p27", add: "highlight" },
  { time: 336, target: ".p28", add: "highlight" },
  { time: 339, target: ".p29", add: "highlight" },
  { time: 341, target: ".p30", add: "highlight" },
  { time: 351, target: ".p31", add: "highlight" },
  { time: 354, target: ".p32", add: "highlight" },
  { time: 369, target: ".p33", add: "highlight" },
  { time: 371, target: ".p34", add: "highlight" },
  { time: 380, target: ".p35", add: "highlight" },
  { time: 381, target: ".p36", add: "highlight" },
  { time: 383, target: ".p37", add: "highlight" },
  { time: 406, target: ".p38", add: "highlight" },
  { time: 409, target: ".p39", add: "highlight" },
  { time: 448, target: ".p40", add: "highlight" },
  { time: 468, target: ".p41", add: "highlight" },
  { time: 478, target: ".p42", add: "highlight" },
  { time: 488, target: ".p43", add: "highlight" },
  { time: 514, target: ".p44", add: "highlight" },
  { time: 515, target: ".p45", add: "highlight" },
  { time: 530, target: ".p46", add: "highlight" },
  { time: 532, target: ".p47", add: "highlight" },
  { time: 535, target: ".p48", add: "highlight" },
  { time: 582, target: ".p49", add: "highlight" },
  { time: 592, target: ".p50", add: "highlight" },

  { time: 15, target: ".popup-fomo", remove: "hide" },
  { time: 17, target: ".popup-fomo", add: "hide" },

  { time: 54, target: ".popup-bartop", remove: "hide" },
  { time: 59, target: ".popup-bartop", add: "hide" },
  { time: 57, target: ".popup-goodsum", remove: "hide" },
  { time: 59, target: ".popup-goodsum", add: "hide" },

  { time: 89, target: ".page", add: "hacker" },
  { time: 95, target: ".page", remove: "hacker" },
  { time: 89, target: ".flex-container-green", remove: "hide" },
  { time: 95, target: ".flex-container-green", add: "hide" },
  { time: 89, target: ".hacker-data", remove: "hide" },
  { time: 95, target: ".hacker-data", add: "hide" },
  { time: 89, target: ".flex-container", add: "hide" },
  { time: 95, target: ".flex-container", remove: "hide" },
  { time: 89, target: ".top-line-green", remove: "hide" },
  { time: 95, target: ".top-line-green", add: "hide" },
  { time: 89, target: ".top-line", add: "hide" },
  { time: 95, target: ".top-line", remove: "hide" },
  { time: 89, target: ".jamesbridle", add: "hide" },
  { time: 95, target: ".jamesbridle", remove: "hide" },
  { time: 89, target: ".jamesbridle-green", remove: "hide" },
  { time: 95, target: ".jamesbridle-green", add: "hide" }, 

  { time: 130, target: ".cat-1", remove: "hide" },
  { time: 130, target: ".cat-2", remove: "hide" },
  { time: 130, target: ".cat-3", remove: "hide" },
  { time: 135, target: ".cat-1", add: "hide" },
  { time: 135, target: ".cat-2", add: "hide" },
  { time: 135, target: ".cat-3", add: "hide" },

  { time: 131, target: ".dog-1", remove: "hide" },
  { time: 131, target: ".dog-2", remove: "hide" },
  { time: 131, target: ".dog-3", remove: "hide" },
  { time: 135, target: ".dog-1", add: "hide" },
  { time: 135, target: ".dog-2", add: "hide" },
  { time: 135, target: ".dog-3", add: "hide" },

  { time: 201.5, target: ".popup-drunk", remove: "hide" },
  { time: 204, target: ".popup-drunk", add: "hide" },

  { time: 205, target: ".blank-backdrop", remove: "hide"},
  { time: 205, target: ".empty-side", remove: "hide"},
  { time: 209, target: ".empty-side", add: "hide"},
  { time: 209, target: ".letter-network", remove: "hide"},
  { time: 209, target: ".letter-network-text", remove: "hide"},
  { time: 214, target: ".letter-network-text", add: "hide"},
  { time: 214, target: ".network-arrows", remove: "hide"},
  { time: 214, target: ".network-arrows-text", remove: "hide"},
  { time: 218, target: ".network-arrows-text", add: "hide"},
  { time: 218, target: ".neural-network-text", remove: "hide"},
  { time: 220, target: ".neural-network-text", add: "hide"},
  { time: 220, target: ".cartoon-houses-and-sat", remove: "hide"},
  { time: 220, target: ".cartoon-houses-and-sat-text", remove: "hide"},
  { time: 224, target: ".cartoon-houses-and-sat-text", add: "hide"},
  { time: 224, target: ".letter-network", add: "hide"},
  { time: 224, target: ".network-arrows", add: "hide"},
  { time: 224, target: ".cartoon-houses-and-sat", add: "hide"},
  { time: 224, target: ".blank-backdrop", add: "hide"},

  { time: 271, target: ".page", add: "dark" },
  { time: 304, target: ".page", remove: "dark" },
  { time: 271, target: ".flex-container-light", remove: "hide" },
  { time: 304, target: ".flex-container-light", add: "hide" },
  { time: 271, target: ".flex-container", add: "hide" },
  { time: 304, target: ".flex-container", remove: "hide" },
  { time: 271, target: ".top-line-light", remove: "hide" },
  { time: 304, target: ".top-line-light", add: "hide" },
  { time: 271, target: ".top-line", add: "hide" },
  { time: 304, target: ".top-line", remove: "hide" },
  { time: 271, target: ".shadow-sites-text", remove: "hide" },
  { time: 273, target: ".shadow-sites-text", add: "hide" },

  { time: 323, target: ".page", add: "sar" },
  { time: 328, target: ".page", remove: "sar" },
  { time: 323, target: ".flex-container-green", remove: "hide" },
  { time: 328, target: ".flex-container-green", add: "hide" },
  { time: 323, target: ".flex-container", add: "hide" },
  { time: 334, target: ".flex-container", remove: "hide" },
  { time: 323, target: ".top-line-yellow", remove: "hide" },
  { time: 328, target: ".top-line-yellow", add: "hide" },
  { time: 323, target: ".top-line", add: "hide" },
  { time: 334, target: ".top-line", remove: "hide" },
  { time: 323, target: ".jamesbridle", add: "hide" },
  { time: 328, target: ".jamesbridle", remove: "hide" },
  { time: 323, target: ".jamesbridle-yellow", remove: "hide" },
  { time: 328, target: ".jamesbridle-yellow", add: "hide" }, 
  { time: 323, target: ".pyramid", remove: "hide" },
  { time: 328, target: ".pyramid", add: "hide" },

  { time: 328, target: ".page", add: "lidar" },
  { time: 334, target: ".page", remove: "lidar" },
  { time: 328, target: ".flex-container-light", remove: "hide" },
  { time: 334, target: ".flex-container-light", add: "hide" },
  { time: 328, target: ".top-line-light", remove: "hide" },
  { time: 334, target: ".top-line-light", add: "hide" },
  { time: 328, target: ".jungle-city", remove: "hide" },
  { time: 334, target: ".jungle-city", add: "hide" },

  { time: 364, target: ".page", add: "hacker" },
  { time: 369, target: ".page", remove: "hacker" },
  { time: 364, target: ".flex-container-green", remove: "hide" },
  { time: 369, target: ".flex-container-green", add: "hide" },
  { time: 364, target: ".flex-container", add: "hide" },
  { time: 369, target: ".flex-container", remove: "hide" },
  { time: 364, target: ".top-line-green", remove: "hide" },
  { time: 369, target: ".top-line-green", add: "hide" },
  { time: 364, target: ".top-line", add: "hide" },
  { time: 369, target: ".top-line", remove: "hide" },
  { time: 364, target: ".jamesbridle", add: "hide" },
  { time: 369, target: ".jamesbridle", remove: "hide" },
  { time: 364, target: ".jamesbridle-green", remove: "hide" },
  { time: 369, target: ".jamesbridle-green", add: "hide" }, 

  { time: 410, target: ".input-ag-right", remove: "hide" },
  { time: 413, target: ".input-ag-right", add: "hide" },

  { time: 448, target: ".blank-backdrop", remove: "hide" },
  { time: 448, target: ".text-one", remove: "hidden"},
  { time: 452, target: ".text-one", add: "hidden"},
  { time: 452, target: ".page", remove: "dark" },
  { time: 452, target: ".map-og", remove: "hidden"},
  { time: 452, target: ".text-two", remove: "hidden"},
  { time: 458, target: ".map-og", add: "hidden"},
  { time: 458, target: ".text-two", add: "hidden"},
  { time: 458, target: ".map-grid", remove: "hidden"},
  { time: 458, target: ".text-three", remove: "hidden"},
  { time: 468, target: ".map-grid", add: "hidden"},
  { time: 468, target: ".text-three", add: "hidden"},
  { time: 468, target: ".blank-backdrop", add: "hide"},

  { time: 491, target: ".page", add: "red" },
  { time: 515, target: ".page", remove: "red" },
  { time: 491, target: ".flex-container-light", remove: "hide" },
  { time: 515, target: ".flex-container-light", add: "hide" },
  { time: 491, target: ".flex-container", add: "hide" },
  { time: 515, target: ".flex-container", remove: "hide" },
  { time: 491, target: ".top-line-yellow", remove: "hide" },
  { time: 515, target: ".top-line-yellow", add: "hide" },
  { time: 491, target: ".top-line", add: "hide" },
  { time: 515, target: ".top-line", remove: "hide" },
  { time: 491, target: ".jamesbridle", add: "hide" },
  { time: 515, target: ".jamesbridle", remove: "hide" },
  { time: 491, target: ".jamesbridle-yellow", remove: "hide" },
  { time: 515, target: ".jamesbridle-yellow", add: "hide" }, 
  { time: 506, target: ".pink-gate", remove: "hidden" },
  { time: 515, target: ".pink-gate", add: "hidden" }, 

  { time: 575, target: ".page", add: "blue" },
  { time: 583, target: ".page", remove: "blue" },
  { time: 575, target: ".bubbles", remove: "hide" },
  { time: 583, target: ".bubbles", add: "hide" },

  { time: 600, target: ".page", add: "blank" },
  { time: 600, target: ".top-line", add: "hide"},
  { time: 600, target: ".flex-container", add: "hide"},
  { time: 600, target: ".title", add: "hide"},
  { time: 600, target: ".jamesbridle", add: "hide"},
  { time: 600, target: ".george", add: "hide"},
  { time: 600, target: ".anna", add: "hide"},
  { time: 600, target: ".setting-text", add: "hide"},
  { time: 600, target: ".map-of-future", remove: "hidden" },
  { time: 608, target: ".page", remove: "blank" },
  { time: 608, target: ".top-line", remove: "hide"},
  { time: 608, target: ".flex-container", remove: "hide"},
  { time: 608, target: ".title", remove: "hide"},
  { time: 608, target: ".jamesbridle", remove: "hide"},
  { time: 608, target: ".george", remove: "hide"},
  { time: 608, target: ".anna", remove: "hide"},
  { time: 608, target: ".setting-text", remove: "hide"},
  { time: 608, target: ".map-of-future", add: "hidden" },
];

