const classChanges = [
  { time: 15, target: ".popup-fomo", remove: "hide" },
  { time: 17, target: ".popup-fomo", add: "hide" },

  { time: 54, target: ".popup-bartop", remove: "hide" },
  { time: 59, target: ".popup-bartop", add: "hide" },
  { time: 57, target: ".popup-goodsum", remove: "hide" },
  { time: 59, target: ".popup-goodsum", add: "hide" },

  { time: 89, target: ".neural-networks-topl", remove: "hide" },
  { time: 90, target: ".neural-networks-topr", remove: "hide" },
  { time: 91, target: ".neural-networks-bottoml", remove: "hide" },
  { time: 92, target: ".neural-networks-bottomr", remove: "hide" },
  { time: 95, target: ".neural-networks-topl", add: "hide" },
  { time: 95, target: ".neural-networks-topr", add: "hide" },
  { time: 95, target: ".neural-networks-bottoml", add: "hide" },
  { time: 95, target: ".neural-networks-bottomr", add: "hide" },

  { time: 130, target: ".cat-1", remove: "hide" },
  { time: 130, target: ".cat-2", remove: "hide" },
  { time: 130, target: ".cat-3", remove: "hide" },
  { time: 135, target: ".cat-1", add: "hide" },
  { time: 135, target: ".cat-2", add: "hide" },
  { time: 135, target: ".cat-3", add: "hide" },

  { time: 131, target: ".dog-1", remove: "hide" },
  { time: 131, target: ".dog-2", remove: "hide" },
  { time: 131, target: ".dog-3", remove: "hide" },
  { time: 135, target: ".dog-1", add: "hide" },
  { time: 135, target: ".dog-2", add: "hide" },
  { time: 135, target: ".dog-3", add: "hide" },

  { time: 201.5, target: ".popup-drunk", remove: "hide" },
  { time: 204, target: ".popup-drunk", add: "hide" },

  { time: 205, target: ".page", add: "blank" },
  { time: 205, target: ".top-line", add: "hide"},
  { time: 205, target: ".flex-container", add: "hide"},
  { time: 205, target: ".title", add: "hide"},
  { time: 205, target: ".jamesbridle", add: "hide"},
  { time: 205, target: ".george", add: "hide"},
  { time: 205, target: ".anna", add: "hide"},
  { time: 205, target: ".setting-text", add: "hide"},
  { time: 205, target: ".empty-side", remove: "hide"},
  { time: 209, target: ".empty-side", add: "hide"},
  { time: 209, target: ".letter-network", remove: "hide"},
  { time: 209, target: ".letter-network-text", remove: "hide"},
  { time: 214, target: ".letter-network-text", add: "hide"},
  { time: 214, target: ".network-arrows", remove: "hide"},
  { time: 214, target: ".network-arrows-text", remove: "hide"},
  { time: 218, target: ".network-arrows-text", add: "hide"},
  { time: 218, target: ".neural-network-text", remove: "hide"},
  { time: 220, target: ".neural-network-text", add: "hide"},
  { time: 220, target: ".cartoon-houses-and-sat", remove: "hide"},
  { time: 220, target: ".cartoon-houses-and-sat-text", remove: "hide"},
  { time: 224, target: ".cartoon-houses-and-sat-text", add: "hide"},
  { time: 224, target: ".letter-network", add: "hide"},
  { time: 224, target: ".network-arrows", add: "hide"},
  { time: 224, target: ".cartoon-houses-and-sat", add: "hide"},
  { time: 224, target: ".page", remove: "blank" },
  { time: 224, target: ".top-line", remove: "hide"},
  { time: 224, target: ".flex-container", remove: "hide"},
  { time: 224, target: ".title", remove: "hide"},
  { time: 224, target: ".jamesbridle", remove: "hide"},
  { time: 224, target: ".george", remove: "hide"},
  { time: 224, target: ".anna", remove: "hide"},
  { time: 224, target: ".setting-text", remove: "hide"},

  { time: 271, target: ".page", add: "dark" },
  { time: 304, target: ".page", remove: "dark" },
  { time: 271, target: ".flex-container-light", remove: "hide" },
  { time: 304, target: ".flex-container-light", add: "hide" },
  { time: 271, target: ".flex-container", add: "hide" },
  { time: 304, target: ".flex-container", remove: "hide" },
  { time: 271, target: ".top-line-light", remove: "hide" },
  { time: 304, target: ".top-line-light", add: "hide" },
  { time: 271, target: ".top-line", add: "hide" },
  { time: 304, target: ".top-line", remove: "hide" },

];
